DRAFT/update eas portal
Consensys/linea-attestation-registry pull request #106
Opened 2023-08-26 02:59 UTC by 0xEillo

## What does this PR do?

This PR is a different implementation of the EASPortal. In this implementation, we maintain use the AbstractPortal contract instead of creating a new EASAbstractPortal. This will allow us to register the EASPortal to the PortalRegistry and avoids custom code for EAS

### Related ticket

Fixes #

### Type of change

- [ ] Chore
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update

## Check list

- [x] Unit tests for any smart contract change
- [ ] Contracts and functions are documented

2023-08-28 13:00 UTC, orbmis requested changes

2023-08-28 14:21 UTC, 0xEillo commented on src/portal/EASPortal.sol
> +  function attest(AttestationRequest memory attestationRequest, bytes[] memory validationPayload) external payable {
Good point, I'll push a fix

2023-08-29 07:57 UTC, orbmis approved these changes

2023-08-29 08:02 UTC, alainncls approved these changes

2023-08-29 08:10 UTC, alainncls requested changes
Improve code coverage

2023-08-29 08:57 UTC, alainncls approved these changes

2023-08-29 09:19 UTC, merged