Feat: As a user, I want to have an example merkle proof module
Consensys/linea-attestation-registry pull request #328
Opened 2023-10-26 06:06 UTC by Builddddder

## What does this PR do?

### Related ticket

Fixes #246 

### Type of change

- [ ] Chore
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update

## Check list

- [x] Unit tests for any smart contract change
- [x] Contracts and functions are documented

2023-10-26 08:36 UTC, orbmis approved these changes

2023-10-26 09:45 UTC, alainncls requested changes

2023-10-26 09:45 UTC, alainncls commented on contracts/src/examples/modules/MerkleProofModule.sol
> +     * @notice We send the a hardcoded third leaf to verify.
I guess the 'a' is a typo?

2023-10-26 09:45 UTC, alainncls commented on contracts/test/example/MerkleProofModule.t.sol
> +  function test_MerkleProofModule_MerkleProofVerifySuccess() public {
The names of the two tests are swapped

2023-10-26 13:19 UTC, Builddddder commented on contracts/src/examples/modules/MerkleProofModule.sol
> +     * @notice We send the a hardcoded third leaf to verify.
Yes, will be fixed

2023-10-26 16:28 UTC, Builddddder commented on contracts/src/examples/modules/MerkleProofModule.sol
> +     * @notice We send the a hardcoded third leaf to verify.
fixed

2023-10-26 16:31 UTC, Builddddder commented on contracts/test/example/MerkleProofModule.t.sol
> +  function test_MerkleProofModule_MerkleProofVerifySuccess() public {
fixed

2023-10-26 16:32 UTC, Builddddder commented on contracts/src/examples/modules/MerkleProofModule.sol
> +     * @notice We send the a hardcoded third leaf to verify.
fixed

2023-10-27 01:10 UTC, Builddddder commented
@alainncls Had changed by comments.Please review again.

2023-10-27 12:20 UTC, alainncls approved these changes

2023-10-27 12:23 UTC, merged