feat: As a user, I want to be able to connect my wallet to Explorer and see the list of my attestations
Consensys/linea-attestation-registry pull request #456
Opened 2023-12-07 10:55 UTC by OliynykPro

## What does this PR do?

- Added my attestation list
- Add `vite-plugin-svgr` library for importing SVG as JSX

### Related ticket
https://github.com/Consensys/linea-attestation-registry/issues/414

2023-12-07 11:26 UTC, orbmis approved these changes

2023-12-07 11:27 UTC, Solniechniy requested changes

2023-12-07 11:27 UTC, Solniechniy commented on explorer/src/utils/dateUtils.ts
> +  return `${dd}.${mm}.${yyyy}, ${hours}:${minutes}`;
moment

2023-12-07 11:37 UTC, voenkomatiwe commented on explorer/src/components/Buttons/index.tsx
> +      className="h-12 px-4 py-3 rounded-md border border-zinc-200 justify-center items-center gap-2 inline-flex text-zinc-950 text-base font-semibold hover:border-slate-500 disabled:opacity-40"
border-zinc-200? text-zinc-950? border-slate-500? use this https://github.com/Consensys/linea-attestation-registry/blob/dev/explorer/tailwind.config.js#L45

2023-12-07 11:37 UTC, voenkomatiwe commented on explorer/src/components/Footer/index.tsx
> +            className="flex justify-center items-center self-center gap-2 hover:underline hover:text-zinc-950"
please change the color here too

2023-12-07 11:37 UTC, voenkomatiwe commented on explorer/src/components/Header/index.tsx
> +          <VeraxLogo />
You need to add the styles that were. As the screen width changes, the logo increases and decreases.
Also, check all the SVGs that you changed.

2023-12-07 11:37 UTC, voenkomatiwe commented on explorer/src/components/InfoBlock/index.tsx
> +      <div className="text-slate-500 text-base font-normal">{message}</div>
text-slate-500

2023-12-07 11:37 UTC, voenkomatiwe commented on explorer/src/pages/Attestations/components/ListSwitcher/index.tsx
>      <div className="inline-flex bg-slate-100 gap-2 mb-6 rounded">
bg-slate-100

2023-12-07 11:37 UTC, voenkomatiwe commented on explorer/src/pages/Attestations/table/columns.tsx
> +import { ColumnDef } from "@tanstack/react-table";
move this file to `linea-attestation-registry/explorer/src/constants/columns/myAttestation.tsx`

2023-12-07 11:37 UTC, voenkomatiwe commented on explorer/src/pages/Attestations/table/components/SortByDate/index.tsx
> +import { ArrowDownUp } from "lucide-react";
is there any point in this component if it already exists https://github.com/Consensys/linea-attestation-registry/blob/dev/explorer/src/components/SortByDate/index.tsx

2023-12-07 11:37 UTC, voenkomatiwe commented on explorer/src/pages/Attestations/table/dataTable.tsx
> +import { flexRender, getCoreRowModel, useReactTable } from "@tanstack/react-table";
is there any point in this component if it already exists https://github.com/Consensys/linea-attestation-registry/blob/dev/explorer/src/components/DataTable/index.tsx

2023-12-07 17:06 UTC, OliynykPro commented on explorer/src/pages/MyAttestations/index.tsx
> +  const handleCopy = (text: string, result: boolean) => {
`CopyToClipboard` it's component from `"react-copy-to-clipboard"` library

2023-12-08 08:49 UTC, voenkomatiwe commented on explorer/src/pages/Attestation/RelatedAttestations/index.tsx
> +import { Link } from "react-router-dom";
here we need to return everything as it was
`import { Link } from "@/components/Link";`

2023-12-08 09:08 UTC, Solniechniy approved these changes

2023-12-08 09:09 UTC, merged