Feat: As a user, I want to be able to see the module details page on Explorer #418
Consensys/linea-attestation-registry pull request #457
Opened 2023-12-07 11:03 UTC by voenkomatiwe

…Explorer #418

## What does this PR do?
(As a user, I want to be able to see the module details page on Explorer #418)[https://github.com/Consensys/linea-attestation-registry/issues/418]

2023-12-07 11:38 UTC, ars9 requested changes

2023-12-07 11:38 UTC, ars9 commented on explorer/src/pages/Module/index.tsx
> +  //todo add loading
Let's add a placeholder Loading component to get rid of all the todos related to it across all files.

2023-12-11 10:26 UTC, Solniechniy commented on explorer/src/constants/columns/attestation.tsx
> +export const attestationColonsOption: ColonsOptions = {
Maybe columns?

2023-12-11 12:37 UTC, ars9 approved these changes
Looks good to me.

2023-12-11 12:37 UTC, merged