feat: as a Portal, I can create an Attestation
Consensys/linea-attestation-registry pull request #69
Opened 2023-08-16 11:03 UTC by 0xEillo

## What does this PR do?

As a Portal SC, I can create an Attestation on the AttestationRegistry. 

Some slight changes to the US. Noteably, in this implementation I assume that it is the Portal's role to construct the Attestation, thereby the attest function directly receives an "Attestation" as a parameter. 

### Related ticket

Fixes #61 and #33

### Type of change

- [ ] Chore
- [ ] Bug fix
- [x] New feature
- [ ] Documentation update

## Check list

- [x] Unit tests for any smart contract change
- [x] Contracts and functions are documented

2023-08-16 11:22 UTC, orbmis commented on src/types/Structs.sol
There seems to be a conflict of conventions here as we have this file and we also have a "structs" folder, and many of the Structs are declared in both places.   It doesn't really matter which convention we use we should pick one and remove the other.

2023-08-16 13:59 UTC, satyajeetkolhapure commented
Currently we have a default portal which has a schema and list of modules. Attestation struct hold schema too. We need to decide which component owns the schema.

2023-08-16 15:03 UTC, satyajeetkolhapure commented
> I think its fine to have a reference to the schemaId in both don't you think?

I can be useful but then there will be extra validations required like portal and attestation having different schema id situation. Also it can be little confusing while implementing portals. Do we have any strong reason to do so?

2023-08-16 15:51 UTC, alainncls commented
@0xEillo let's push the tests under `test/unit` and leave the mocks where they are.
This way, by modifying the command in `smart-contracts-test.yml`, we'll be able to get the coverage we want (only on the real tests and not the mocks).

2023-08-18 10:21 UTC, orbmis requested changes

2023-08-18 10:21 UTC, orbmis commented on src/AttestationRegistry.sol
> +    attestations[attestationId].revoked = true;
Removing this comment because this is being addressed by another story

2023-08-18 11:12 UTC, 0xEillo commented on test/AttestationRegistry.t.sol
> +  function test_attest(Attestation memory attestation) public {
Not a dumb question. In foundry you can have parameters to test functions. Foundry will then create thousands of iterations of an attestation and test that they all work. i.e Fuzzing

2023-08-18 11:21 UTC, 0xEillo commented on src/AttestationRegistry.sol
> +    attestations[attestation.attestationId] = attestation;
Yes, we can do this inside the Abstract Portal where the attestation will be created

2023-08-18 11:21 UTC, 0xEillo commented on src/AttestationRegistry.sol
> +    attestations[attestation.attestationId] = attestation;
We can do this check in the Portal as well probably

2023-08-21 13:56 UTC, alainncls approved these changes

2023-08-21 13:56 UTC, merged