feat(explorer): As a user, I want to see Expired and Revoked Attestations with a watermark on the Subject page
Consensys/linea-attestation-registry pull request #794
Opened 2024-11-06 10:37 UTC by satyajeetkolhapure

## What does this PR do?

For revoked attestations a watermark with red colour and revoked text is added.
For expired attestations card is greyed out

### Related ticket

Fixes #755 

### Type of change

- [ ] Chore
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update

## Check list

- [ ] Unit tests for any smart contract change
- [ ] Contracts and functions are documented

2024-11-07 03:49 UTC, alainncls requested changes

2024-11-07 03:49 UTC, alainncls commented on explorer/src/assets/watermarks/revoked-watermark.svg
I don't think we should use an SVG here. We wouldn't be able to translate the 'Revoked' line, etc.
What about some CSS to apply the red word on top of the Card?

2024-11-07 09:35 UTC, satyajeetkolhapure commented on explorer/src/assets/watermarks/revoked-watermark.svg
CSS is slightly difficult because of the variable card size, there will be calculations on x,y co-ordinates when window size changes. We can remove the text from svg and manage it with css. wdyt?

2024-11-08 10:43 UTC, alainncls commented on explorer/src/pages/Attestation/components/AttestationCard/index.tsx
> +        )}
```suggestion
      {revoked && (
        <div
          className="absolute inset-0 flex items-center justify-center text-red-500 text-4xl md:text-6xl font-bold opacity-50 pointer-events-none"
          style={{ transform: "rotate(-45deg)" }}
        >
          Revoked
        </div>
      )}
```

2024-11-08 10:43 UTC, alainncls commented on explorer/src/assets/watermarks/revoked-watermark.svg
Let me try something here: https://github.com/Consensys/linea-attestation-registry/pull/794/files#r1834127096

2024-11-08 16:54 UTC, alainncls approved these changes

2024-11-08 17:10 UTC, merged