[US] As a user, I want to query the current version of the registry
Consensys/linea-attestation-registry pull request #85
Opened 2023-08-21 15:30 UTC by orbmis

## What does this PR do?

As a user, I want to query the current version of the registry

This PR basically sets the version in the attestation registry, and allows the contract owner to increment it

### Related ticket

Fixes 79

### Type of change

- [ ] Chore
- [ ] Bug fix
- [*] New feature
- [ ] Documentation update

## Check list

- [*] Unit tests for any smart contract change
- [*] Contracts and functions are documented

2023-08-21 15:51 UTC, alainncls requested changes

2023-08-21 15:51 UTC, alainncls commented on src/AttestationRegistry.sol
> +    return version;
```suggestion
return version++;
```
Wdyt?

2023-08-21 15:51 UTC, alainncls commented on test/AttestationRegistry.t.sol
> +    attestationRegistry.incrementVersionNumber();
Maybe check the returned value is `1`?

2023-08-21 15:51 UTC, 0xEillo reviewed
Do we want to implement semantic versioning here? so following the:

numerical components: MAJOR.MINOR.PATCH

where version would be a string concatenation

2023-08-22 15:30 UTC, alainncls requested changes
I've just realized `Ownable` is not "upgradeable".
Open Zeppelin is working on a v5 for their contracts, including a `OwnableUpgradeable`. In the meantime we can't use `Ownable` in a contract that will be made upgradeable (cf. #83 )

2023-08-23 08:37 UTC, alainncls approved these changes

2023-08-23 08:37 UTC, merged